<footer class="white-wrapper">
  <div class="container">
    <div class="row justify-content-between">
      <div class="col-md-4 text-center">
        <ul class="list-inline social-links wow">
          <li>
            <a href="https://github.com/ffdghs" target="_blank"><i class="fab fa-github"></i></a>
          </li>
          <li>
            <a href="https://www.pinterest.fr/nicolas5289" target="_blank"><i class="fab fa-pinterest-p"></i></a>
          </li>
          <li>
            <a href="https://discord.com/nnico#9542" target="_blank"><i class="fab fa-discord"></i></a>
          </li>
          <li>
            <a href="https://500px.com/p/ffdghs?view=photos" target="_blank"><i class="fab fa-500px"></i></a>
          </li>
          <li>
            <a href="https://www.last.fm/user/ffdghs" target="_blank"><i class="fab fa-lastfm"></i></a>
          </li>
          <li>
            <a href="https://www.linkedin.com/in/nicolas-nielsen/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
          </li>
        </ul>
      </div>

      <div class="col-md-4">
        <!-- <div id="message"></div>
        <form method="post" action="index.php" id="contactform" class="main-contact-form wow">
          <input type="text" class="form-control col-md-4" name="name" placeholder="Your Name *" id="name" required
            data-validation-required-message="Please enter your name." />
          <input type="text" class="form-control col-md-4" name="email" placeholder="Your Email *" id="email" required
            data-validation-required-message="Please enter your email address." />
          <textarea name="comments" class="form-control" id="comments" placeholder="Your Message *" required
            data-validation-required-message="Please enter a message."></textarea>
          <input class="btn btn-primary mt30 btn-white pull-right" type="submit" name="submit" value="Submit" />
        </form> -->
      </div>

      <div class="col-md-4 wow text-right" id="contacts">
        <h2 class="text-right">Contact</h2>
        <p>nnielsen.dev@gmail.com</p>
        <p>06 86 46 86 82</p>
        <p>207 rue La Fayette, Paris 75010</p>
      </div>
    </div>
  </div>
</footer>