<header id="headerwrap" class="backstretched fullheight no-overlay" data-parallax="scroll" data-image-src="assets/img/bg-masthead.jpg" data-speed="0.7">
  <div class="section-inner pad-top-200">
      <div class="container">
          <div class="intro-text vertical-center text-center smoothie">
              <div class="intro-heading wow fadeIn text-center heading-font" data-wow-delay="0.2s">Nicolas Nielsen</div>
              <div class="intro-sub-heading wow fadeIn text-center secondary-font" data-wow-delay="0.4s">Développeur Web :
                  <span class="rotate">Intégration, Javascript, PHP, Symfony, React</span>
              </div>
              <a href="#about" class="btn btn-primary btn-xl" id="btn-esp">En savoir plus</a>
          </div>
      </div>
  </div>
</header>