<nav class="navbar navbar-default navbar-fixed-top fadeInDown" data-wow-delay="0.5s">
  <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navigation">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand smoothie" href="index.html">Portfolio</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div id="main-navigation">
          <ul class="nav navbar-nav navbar-right">
              <li>
                  <a href="#page-top">Home</a>
              </li>
              <li>
                  <a href="#about">About</a>
              </li>
              <li>
                  <a href="#skills">Compétences</a>
              </li>
              <li>
                  <a href="#portfolio">Portfolio</a>
              </li>
              <!-- <li><a href="#search"><i class="pe-7s-search"></i></a></li>
              <li><a href="javascript:void(0);" class="side-menu-trigger hidden-xs"><i class="fa fa-bars"></i></a></li> -->
          </ul>
      </div>
      <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>