<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navigation">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand smoothie" href="index.php">Portfolio</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div id="main-navigation">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="index.php#page-top">Home</a>
        </li>
        <li>
          <a href="index.php#about">About</a>
        </li>
        <li>
          <a href="index.php#skills">Compétences</a>
        </li>
        <li>
          <a href="index.php#portfolio">Portfolio</a>
        </li>
        <li>
          <a href="index.php#lab">Le Lab°</a>
        </li>
        <!-- <li><a href="#search"><i class="pe-7s-search"></i></a></li>
              <li><a href="javascript:void(0);" class="side-menu-trigger hidden-xs"><i class="fa fa-bars"></i></a></li> -->
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>