<script src="assets/js/jquery.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/plugins.js"></script>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="assets/js/init.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        'use strict';
        jQuery('#headerwrap').backstretch([
            "assets/img/bg-masthead"
            // "assets/img/SAM_8915.jpg",
            // "assets/img/SAM_9529.jpg"
        ], {
            duration: 8000,
            fade: 500
        });
    });
</script>