<!DOCTYPE html>
<html lang="fr">

<head>
  <?php include 'include/basehead.phtml' ?>
</head>

<body id="page-top" class="index">
  <div class="master-wrapper">
    <!-- Navigation -->
    <?php include 'include/nav.phtml' ?>

    <?php include 'include/header.phtml' ?>

    <section id="about">
      <div class="row">
        <div class="col">
          <h2>Développeur Web</h2>
          <p class="mt-4">En reconversion comme dev web.</p>
          <p>Curieux et d'une logique assez développée, la programmation a souvent fait parti de mon environnement à petite échelle, que ce soit pour créer des applications en vba au cours de mon expérience professionnelle ou pour tweeker mes logiciels/os au quotidien.</p>
          <a href="./CV_Nicolas_Nielsen.pdf" class="btn btn-primary btn-xl" id="btn-cv" target="_blank">Télécharger mon cv</a>
        </div>
      </div>
    </section>

    <section id="skills">
      <h2 class="mb-4">Compétences</h2>
      <div class="row">
        <div class="skill-type">
          <h3>Intégration</h3>
          <hr>
          <div>
            <div>
              <img src="assets/img/skills/html5.png" alt="">
              <p>HTML</p>
            </div>
            <div>
              <img src="assets/img/skills/css3.png" alt="">
              <p>CSS</p>
            </div>
            <div>
              <img src="assets/img/skills/bootstrap.png" alt="">
              <p>Bootstrap</p>
            </div>
          </div>
        </div>
        <div class="skill-type">
          <h3>Front</h3>
          <hr>
          <div>
            <div>
              <img src="assets/img/skills/javascript.png" alt="">
              <p>JavaScript</p>
            </div>
            <div>
              <img src="assets/img/skills/react.png" alt="">
              <p>React.js</p>
            </div>
            <div>
              <img src="assets/img/skills/ajax.png" alt="">
              <p>Ajax</p>
            </div>
          </div>
        </div>
        <div class="skill-type">
          <h3>Back</h3>
          <hr>
          <div>
            <div>
              <img src="assets/img/skills/php.png" alt="">
              <p>PHP</p>
            </div>
            <div>
              <img src="assets/img/skills/sql.png" alt="">
              <p>SQL</p>
            </div>
            <div>
              <img src="assets/img/skills/symfony.png" alt="">
              <p>Symfony</p>
            </div>
            <div>
              <img src="assets/img/skills/twig.png" alt="">
              <p>Twig</p>
            </div>
            <div>
              <img src="assets/img/skills/mongodb.png" alt="">
              <p>MongoDB</p>
            </div>
            <div>
              <img src="assets/img/skills/nodejs.png" alt="">
              <p>Node.js</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="white-bg" id="portfolio">
      <div class="section-inner masonry-portfolio container">
        <h2 class="mb-3">Portfolio</h2>
        <div>
          <div class="row">
            <div class="col-md-12 text-center mb50">
              <ul class="masonry-portfolio-filters mb30 list-inline wow animated" style="visibility: visible;">
                <!-- <li><a class="btn btn-primary active" href="#" data-filter="*">All</a></li> -->
                <li><a class="btn btn-primary" href="#" data-filter=".apps">Apps (<?= $projectsCount['nbre'] ?>)</a></li>
                <li><a class="btn btn-primary" href="#" data-filter=".photography">Photography (<?= $picturesCount['nbre'] ?>)</a></li>
                <!-- <li><a class="btn btn-primary" href="#" data-filter=".design">Design</a></li>
                <li><a class="btn btn-primary" href="#" data-filter=".video">Video</a></li> -->
              </ul>
            </div>
          </div>
        </div>
        <div>
          <ul class="masonry-portfolio-items nopadding-lr isotope list-unstyled">
            <?php foreach ($projects as $project) { ?>
              <li class="col-sm-4 col-xs-6 masonry-portfolio-item nopadding-lr apps isotope-item hover-item">
                <img src="assets/img/<?= $project['img'] ?>" class="img-responsive smoothie" alt="">
                <div class="overlay-item-caption smoothie"></div>
                <div class="hover-item-caption smoothie">
                  <div class="vertical-center smoothie">
                    <h3 class="smoothie mb30"><a href="single-portfolio-fullscreen.html" title="view project"><?= $project['title'] ?></a></h3>
                    <a href="assets/img/<?= $project['img_full'] ?>" title="View Gallery" class="btn btn-primary lb-link smoothie">Zoom</a>
                    <a href="details.php?project=<?= $project['id'] ?>" class="smoothie btn btn-primary">View</a>
                    <p class="smoothie mt30"><?= date('F-y',strtotime($project['creation_date']))  ?></p>
                  </div>
                </div>
              </li>
            <?php } ?>

            <?php foreach ($pictures as $picture) { ?>
              <li class="col-sm-4 col-xs-6 masonry-portfolio-item nopadding-lr photography isotope-item hover-item">
                <img src='<?= $picture['url_picture'] ?>' alt='by Nicolas Nielsen on 500px.com' class="img-responsive smoothie">
                <div class="overlay-item-caption smoothie"></div>
                <div class="hover-item-caption smoothie">
                  <div class="vertical-center smoothie">
                    <h3 class="smoothie mb30"><a href="single-portfolio.html" title="view project"><?= $picture['title'] ?></a></h3>
                    <a href="<?= $picture['url_picture'] ?>" title="View Gallery" class="btn btn-primary lb-link smoothie">Zoom</a>
                    <a href="<?= $picture['url_500px'] ?>" class="smoothie btn btn-primary" target="_blank">View</a>
                  </div>
                </div>
              </li>
            <?php } ?>
          </ul>
        </div>
      </div>
    </section>

    <section class="dark-wrapper" id="lab">
      <div class="section-inner">
        <div class="container">
          <div class="row">
            <!-- <div class="col-md-4">
              <div class="widget about-us-widget">
                <h4 class="widget-title"><strong>Global</strong> Coverage</h4>
                <p>Professionally monetize team building materials for 24/7 results. Holisticly transition corporate platforms vis-a-vis cutting-edge experiences. Dynamically strategize ubiquitous applications for premier initiatives. Interactively seize resource sucking niche markets.</p>
              </div>
            </div>
            <div class="col-md-4">
              <div class="widget">
                <h4 class="widget-title"><strong>Latest</strong> Articles</h4>
                <div>
                  <div class="media">
                    <div class="pull-left">
                      <img class="widget-img" src="assets/img/widget/widget1.jpg" alt="">
                    </div>
                    <div class="media-body">
                      <span class="media-heading"><a href="#">Blog Post A</a></span>
                      <small class="muted">Posted 14 April 2015</small>
                    </div>
                  </div>
                  <div class="media">
                    <div class="pull-left">
                      <img class="widget-img" src="assets/img/widget/widget2.jpg" alt="">
                    </div>
                    <div class="media-body">
                      <span class="media-heading"><a href="#">Blog Post B</a></span>
                      <small class="muted">Posted 14 April 2015</small>
                    </div>
                  </div>
                </div>
              </div>
            </div> -->
            <div class="col-md-12">
              <div class="widget">
                <h2 class="widget-title">Le Lab°</h2>
                <div class="tagcloud col-md-6">
                  <a href="./lab/js/color-changer/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript">Color Changer</a>
                  <a href="./lab/js/counter/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript">Counter</a>
                  <a href="./lab/js/datagouv/client/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript/AJAX/PHP/SQL">Formulaire Régions/Départements/Villes</a>
                  <a href="./lab/js/diaporama/diaporama.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript">Diaporama</a>
                  <a href="./lab/js/FAQ/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript">FAQ</a>
                  <a href="./lab/js/modal/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript">Modal</a>
                  <a href="./lab/js/pays/client/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript/AJAX/PHP">Sélecteur Pays</a>
                  <a href="./lab/js/review-carousel/index.html" class="tag-link btn btn-theme btn-white btn-xs smoothie" title="Javascript">Review Carousel</a>
                </div>
                <div>
                  <iframe src="" frameborder="0" width='100%' height="1000px" style="display:none"></iframe>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <?php include 'include/footer.phtml';?>

  </div>

  <div class="flexpanel">
    <div class="viewport-wrap">
      <div class="viewport">
        <div class="widget mb50">
          <h4 class="widget-title">Latest Articles</h4>
          <div>
            <div class="media">
              <div class="pull-left">
                <img class="widget-img" src="assets/img/widget/widget1.jpg" alt="">
              </div>
              <div class="media-body">
                <span class="media-heading"><a href="#">Panic In London</a></span>
                <small class="muted">Posted 14 April 2015</small>
              </div>
            </div>
            <div class="media">
              <div class="pull-left">
                <img class="widget-img" src="assets/img/widget/widget2.jpg" alt="">
              </div>
              <div class="media-body">
                <span class="media-heading"><a href="#">New iPhone News</a></span>
                <small class="muted">Posted 14 April 2015</small>
              </div>
            </div>
            <div class="media">
              <div class="pull-left">
                <img class="widget-img" src="assets/img/widget/widget3.jpg" alt="">
              </div>
              <div class="media-body">
                <span class="media-heading"><a href="#">Our Year In Review</a></span>
                <small class="muted">Posted 14 April 2015</small>
              </div>
            </div>
            <div class="media">
              <div class="pull-left">
                <img class="widget-img" src="assets/img/widget/widget4.jpg" alt="">
              </div>
              <div class="media-body">
                <span class="media-heading"><a href="#">jQuery Tutorial</a></span>
                <small class="muted">Posted 14 April 2015</small>
              </div>
            </div>
            <div class="media">
              <div class="pull-left">
                <img class="widget-img" src="assets/img/widget/widget5.jpg" alt="">
              </div>
              <div class="media-body">
                <span class="media-heading"><a href="#">Sheen Interview</a></span>
                <small class="muted">Posted 14 April 2015</small>
              </div>
            </div>
          </div>
        </div>
        <div class="widget mb50">
          <h4 class="widget-title"><strong>Latest</strong> Articles</h4>
          <div class="tagcloud">
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Local</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Business</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Media</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Photogtraphy</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Aid</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Fashion</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">News</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Cars</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Global Affairs</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Music</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">Downloads</a>
            <a href="#" class="tag-link btn btn-theme btn-xs" title="3 topics">MP3</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <?php include 'include/scripts.phtml' ?>
  <script src="assets/js/index.js"></script>
</body>

</html>